### ISSUE TITLE
Question about LocalHost

### ISSUE THREAD

**Issue by kresnal** [point85/OEE-Domain#13]
https://github.com/point85/OEE-Domain/blob/a7306013c938b30d1073fbbf02e3c988061c8eaf/src/main/java/org/point85/domain/collector/CollectorService.java#L1058

Dear Mr Kent,
I would like to ask question about usage of  LocalHost. With this, the Collector  service must be running in the same network and cannot run independently. Is that correct?

**Comment by point85** [comment]
A collector process can run at any IP address. I have a demo collector running in a Linux VM hosted by AWS Light Sail cloud. When in the cloud the port has to be open

**Comment by kresnal** [comment]
Hi Mr Kent,

I am trying to run with this scenario:
1. DB in cloud 
2. Collector (Wrapper) service in cloud 

Both in gcp. I run the designer in my local laptop. I could connect to DB from Designer. 
I've been following your Started Guide (https://github.com/point85/OEE-Designer/blob/master/docs/Point85%20OEE%20User%20Guide.pdf). So when configuring Data Collection (page 10 & 11), I've put public cloud IP address. However, when I inspect wrapper logging, it will only bind to VM local IP address. As the result, test alway failed.
I cannot find a setting to change the binding inside wrapper.conf file.

**Comment by point85** [comment]
Hello kresnal,
In my AWS Light Sail instance, the Linux wrapper collector daemon process
is connected to the local demo HSQL database running at a public static IP
address of 52.37.56.187 using "localhost".  Here is the configuration from
wrapper.conf:
# Application parameters.
# main class
wrapper.app.parameter.1=org.point85.app.collector.InProcessCollector
# JDBC connection
wrapper.app.parameter.2=jdbc:hsqldb:hsql://localhost/OEE
# user name
wrapper.app.parameter.3=SA

You could try changing "localhost" to 52.37.56.187 if you want to try my
demo database.

GCP may not allow "localhost", in which case try the 127.0.0.1 address
instead.

Regards,
Kent Randall

**Comment by point85** [comment]
First verify that all five desktop GUI applications (Designer, Monitor,
Operator, Collector and Tester) can connect successfully to your database
in the Cloud using the publicly exposed IP address.  Now, configure the
wrapper collector running locally to connect to the cloud database
(wrapper.app.parameter.2).  For these tests, you can turn on trace level
logging in log4j.properties file like this:
# Hibernate specific
# basic log level for all Hibernate messages:
log4j.logger.org.hibernate=trace

# runtime SQL statements and parameters:
log4j.logger.org.hibernate.SQL=trace

# Log JDBC bind parameter runtime arguments:
log4j.logger.org.hibernate.type=trace

# Hikari database connection pool
log4j.logger.com.zaxxer=trace
This will give you a lot of data and you can back it off to "info" level to
get less debug output.

Now, if all of these applications run correctly, and the wrapper collector
in the Cloud gives an error, inspect the log files for more information.
